### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by quisar** [bertptrs/tracing-mutex#12]
@bertptrs Any chance you could do a new release of tracing-mutex. There is quite a number of changes and fixes since 1.0.2?

Thanks!

**Comment by bertptrs** [comment]
Yes, I'll try to patch up a release later today (CEST). I still need to do minor cleanup and fix the changelog, but otherwise should be simple enough. :+1:

**Comment by quisar** [comment]
Thanks. I have another PR that would be nice to have.

**Comment by quisar** [comment]
@bertptrs Any news?
